include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - android/**
    - ios/**
    - linux/**
    - macos/**
    - web/**
    - windows/**

linter:
  rules:
    public_member_api_docs: false
    unnecessary_type_name_in_constructor: false
