name: securedelivery_mobile
description: SecureDelivery mobile application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.13.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0